export const OPERATION_STATE = {
  CREATED: 'CREATED',
  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export type OperationState =
  (typeof OPERATION_STATE)[keyof typeof OPERATION_STATE];
